const showQuery ={
    createNew: () => `INSERT INTO shows (show_name, show_type, about, img, img_b, category, sub_category, video_type, v_link, host_id, host_name, host_img, credits, show_date, start_time, end_time, price, payment, patreon, wp_title, webpage, eighteen_plus, booked, paid, canceled, verified) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
    findAll: () => `SELECT * FROM shows`,
    findAllPref:  () => `SELECT * FROM shows WHERE category='performance'`,
    findAllPrefStor:  () => `SELECT * FROM shows WHERE category='performance' AND sub_category='story'`,
    findAllPrefPlay:  () => `SELECT * FROM shows WHERE category='performance' AND sub_category='play'`,
    findAllPrefMixed:  () => `SELECT * FROM shows WHERE category='performance' AND sub_category='mixed'`,
    findAllPrefVar:  () => `SELECT * FROM shows WHERE category='performance' AND sub_category='variety'`,
    findAllPrefEdu:  () => `SELECT * FROM shows WHERE category='performance' AND sub_category='educate'`,
    findAllPrefBlog:  () => `SELECT * FROM shows WHERE category='performance' AND sub_category='blog'`,
    findAllMuse:  () => `SELECT * FROM shows WHERE category='music'`,
    findAllMuseAcu:  () => `SELECT * FROM shows WHERE category='music' AND sub_category='acoustic'`,
    findAllMuseEdm:  () => `SELECT * FROM shows WHERE category='music' AND sub_category='edm'`,
    findAllMuseDj:  () => `SELECT * FROM shows WHERE category='music' AND sub_category='dj'`,
    findAllMuseMix:  () => `SELECT * FROM shows WHERE category='music' AND sub_category='mixed'`,
    findAllMuseVar:  () => `SELECT * FROM shows WHERE category='music' AND sub_category='variety'`,
    findAllMuseEdu:  () => `SELECT * FROM shows WHERE category='music' AND sub_category='educate'`,
    findAllMuseBlog:  () => `SELECT * FROM shows WHERE category='music' AND sub_category='blog'`,
    findAllVis:  () => `SELECT * FROM shows WHERE category='visual'`,
    findAllVisAna:  () => `SELECT * FROM shows WHERE category='visual' AND sub_category='analog'`,
    findAllVisDig:  () => `SELECT * FROM shows WHERE category='visual' AND sub_category='digital'`,
    findAllVisMix:  () => `SELECT * FROM shows WHERE category='visual' AND sub_category='mixed'`,
    findAllVisVar:  () => `SELECT * FROM shows WHERE category='visual' AND sub_category='variety'`,
    findAllVisEdu:  () => `SELECT * FROM shows WHERE category='visual' AND sub_category='educate'`,
    findAllVisBlog:  () => `SELECT * FROM shows WHERE category='visual' AND sub_category='blog'`,
    findAllLife:  () => `SELECT * FROM shows WHERE category='life'`,
    findAllLifeCouns:  () => `SELECT * FROM shows WHERE category='life' AND sub_category='counseling'`,
    findAllLifeCook:  () => `SELECT * FROM shows WHERE category='life' AND sub_category='cooking'`,
    findAllLifeLH:  () => `SELECT * FROM shows WHERE category='life' AND sub_category='lifehack'`,
    findAllLifeVar:  () => `SELECT * FROM shows WHERE category='life' AND sub_category='variety'`,
    findAllLifeEdu:  () => `SELECT * FROM shows WHERE category='life' AND sub_category='educate'`,
    findAllLifeBlog:  () => `SELECT * FROM shows WHERE category='life' AND sub_category='blog'`,
    findAllSpirt:  () => `SELECT * FROM shows WHERE category='spiritual'`,
    findAllSpirtGuid:  () => `SELECT * FROM shows WHERE category='spiritual' AND sub_category='guide'`,
    findAllSpirtSpell:  () => `SELECT * FROM shows WHERE category='spiritual' AND sub_category='spells'`,
    findAllSpirtRead:  () => `SELECT * FROM shows WHERE category='spiritual' AND sub_category='readings'`,
    findAllSpirtVar:  () => `SELECT * FROM shows WHERE category='spiritual' AND sub_category='variety'`,
    findAllSpirtEdu:  () => `SELECT * FROM shows WHERE category='spiritual' AND sub_category='educate'`,
    findAllSpirtBlog:  () => `SELECT * FROM shows WHERE category='spiritual' AND sub_category='blog'`,
    findByEpis: () => `SELECT id, show_name, host_id, category, sub_category, eighteen_plus FROM shows WHERE host_id = ? AND show_type = 'episodical' OR show_type = "live_show_epis"`,
    findById: () => `SELECT * FROM shows WHERE id = ?`,
    findByHost: () => `SELECT * FROM shows WHERE host_id = ?`,
    findAllKF: () =>`SELECT * FROM shows WHERE eighteen_plus = 0`,
    findKFById: () =>`SELECT * FROM shows WHERE eighteen_plus = 0 and id=?`,
    findAllKFFree: () =>`SELECT * FROM shows WHERE eighteen_plus = 0 and paid = 0 `,
    updateById: () => `UPDATE shows SET ? WHERE ? AND host_id = ?`,
    deleteById: () => `DELETE FROM shows WHERE id=? AND host_id = ?`
};
// May need to apply "AND userid = {currentuser} OR Management = true"

module.exports = showQuery; 