const showQuery ={
    createNew: () => `INSERT INTO shows (show_name, show_type, about, img, img_b, catagory, sub_catagory, v_link, host_id, host_name, host_img, payment, patreon, wp_title, webpage, eighteen_plus, booked, paid, canceled, entertain ,couns, relig) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
    findAll: () => `SELECT * FROM shows`,
    findAllEnt:  () => `SELECT * FROM shows WHERE entertain=1`,
    findAllCouns:  () => `SELECT * FROM shows WHERE couns=1`,
    findAllRelig: () => `SELECT * FROM shows WHERE relig=1`,
    findAllPref:  () => `SELECT * FROM shows WHERE catagory='performance'`,
    findAllPrefStor:  () => `SELECT * FROM shows WHERE catagory='performance' AND sub_catagory='story'`,
    findAllPrefPlay:  () => `SELECT * FROM shows WHERE catagory='performance' AND sub_catagory='play'`,
    findAllPrefMixed:  () => `SELECT * FROM shows WHERE catagory='performance' AND sub_catagory='mixed'`,
    findAllPrefVar:  () => `SELECT * FROM shows WHERE catagory='performance' AND sub_catagory='variety'`,
    findAllPrefEdu:  () => `SELECT * FROM shows WHERE catagory='performance' AND sub_catagory='educate'`,
    findAllPrefBlog:  () => `SELECT * FROM shows WHERE catagory='performance' AND sub_catagory='blog'`,
    findAllMuse:  () => `SELECT * FROM shows WHERE catagory='music'`,
    findAllMuseAcu:  () => `SELECT * FROM shows WHERE catagory='music' AND sub_catagory='acoustic'`,
    findAllMuseEdm:  () => `SELECT * FROM shows WHERE catagory='music' AND sub_catagory='edm'`,
    findAllMuseDj:  () => `SELECT * FROM shows WHERE catagory='music' AND sub_catagory='dj'`,
    findAllMuseMix:  () => `SELECT * FROM shows WHERE catagory='music' AND sub_catagory='mixed'`,
    findAllMuseVar:  () => `SELECT * FROM shows WHERE catagory='music' AND sub_catagory='variety'`,
    findAllMuseEdu:  () => `SELECT * FROM shows WHERE catagory='music' AND sub_catagory='educate'`,
    findAllMuseBlog:  () => `SELECT * FROM shows WHERE catagory='music' AND sub_catagory='blog'`,
    findAllVis:  () => `SELECT * FROM shows WHERE catagory='visual'`,
    findAllVisAna:  () => `SELECT * FROM shows WHERE catagory='visual' AND sub_catagory='analog'`,
    findAllVisDig:  () => `SELECT * FROM shows WHERE catagory='visual' AND sub_catagory='digital'`,
    findAllVisMix:  () => `SELECT * FROM shows WHERE catagory='visual' AND sub_catagory='mixed'`,
    findAllVisVar:  () => `SELECT * FROM shows WHERE catagory='visual' AND sub_catagory='variety'`,
    findAllVisEdu:  () => `SELECT * FROM shows WHERE catagory='visual' AND sub_catagory='educate'`,
    findAllVisBlog:  () => `SELECT * FROM shows WHERE catagory='visual' AND sub_catagory='blog'`,
    findAllLife:  () => `SELECT * FROM shows WHERE catagory='life'`,
    findAllLifeCouns:  () => `SELECT * FROM shows WHERE catagory='life' AND sub_catagory='counseling'`,
    findAllLifeCook:  () => `SELECT * FROM shows WHERE catagory='life' AND sub_catagory='cooking'`,
    findAllLifeLH:  () => `SELECT * FROM shows WHERE catagory='life' AND sub_catagory='lifehack'`,
    findAllLifeVar:  () => `SELECT * FROM shows WHERE catagory='life' AND sub_catagory='variety'`,
    findAllLifeEdu:  () => `SELECT * FROM shows WHERE catagory='life' AND sub_catagory='educate'`,
    findAllLifeBlog:  () => `SELECT * FROM shows WHERE catagory='life' AND sub_catagory='blog'`,
    findAllSpirt:  () => `SELECT * FROM shows WHERE catagory='spiritual'`,
    findAllSpirtGuid:  () => `SELECT * FROM shows WHERE catagory='spiritual' AND sub_catagory='guide'`,
    findAllSpirtSpell:  () => `SELECT * FROM shows WHERE catagory='spiritual' AND sub_catagory='spells'`,
    findAllSpirtRead:  () => `SELECT * FROM shows WHERE catagory='spiritual' AND sub_catagory='readings'`,
    findAllSpirtVar:  () => `SELECT * FROM shows WHERE catagory='spiritual' AND sub_catagory='variety'`,
    findAllSpirtEdu:  () => `SELECT * FROM shows WHERE catagory='spiritual' AND sub_catagory='educate'`,
    findAllSpirtBlog:  () => `SELECT * FROM shows WHERE catagory='spiritual' AND sub_catagory='blog'`,
    findByEpis: () => `SELECT id, show_name, show_type, img, catagory, sub_catagory FROM shows WHERE host_id = ? AND show_type = 'episodical' OR show_type = "live_show_epis"`,
    findById: () => `SELECT * FROM shows WHERE id = ?`,
    findByHost: () => `SELECT * FROM shows WHERE host_id = ?`,
    findAllKF: () =>`SELECT * FROM shows WHERE eighteen_plus = 0`,
    findKFById: () =>`SELECT * FROM shows WHERE eighteen_plus = 0 and id=?`,
    findAllKFFree: () =>`SELECT * FROM shows WHERE eighteen_plus = 0 and paid = 0 `,
    updateById: () => `UPDATE shows SET ? WHERE ? AND host_id = ?`,
    deleteById: () => `DELETE FROM shows WHERE id=? AND host_id = ?`
};
// May need to apply "AND userid = {currentuser} OR Management = true"

module.exports = showQuery; 